# Generated by Django 4.1.1 on 2023-05-30 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('identi', models.CharField(default='None', max_length=300, null=True)),
                ('final_result', models.IntegerField(default=0, null=True)),
                ('submissionstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='videoAns',
            fields=[
                ('ansId', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('identi', models.CharField(default='None', max_length=300, null=True)),
                ('videoAns', models.FileField(blank=True, upload_to='media')),
                ('trasnscript', models.CharField(max_length=10000, null=True)),
                ('answer_accurecy', models.IntegerField(default=0, null=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.question')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
